"""update table

Revision ID: 552be59e5e44
Revises: 161cc5c7ad1a
Create Date: 2026-09-22 22:30:05.281666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '552be59e5e44'
down_revision = '161cc5c7ad1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('courses_lecturer_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'lecturers', ['lecturer_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('courses_lecturer_id_fkey'), 'users', ['lecturer_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
